import patterns.observer.Main;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public static void main(String[] args) {
        var observer = new Main();
        observer.run();
    }
}
